// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOOiBkPX9NAAriuF_sJjWs50KaoDE4TSA',
    appId: '1:514383062976:web:96896d53d0a190994d4a25',
    messagingSenderId: '514383062976',
    projectId: 'smarthomeapp-77bf1',
    authDomain: 'smarthomeapp-77bf1.firebaseapp.com',
    storageBucket: 'smarthomeapp-77bf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnZRq47DV1-ezHa-Fnu4bA8KVma7TY3ds',
    appId: '1:514383062976:android:dcbc2bc3582c818c4d4a25',
    messagingSenderId: '514383062976',
    projectId: 'smarthomeapp-77bf1',
    storageBucket: 'smarthomeapp-77bf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpGoICQrn1SxPhtJ3H3wQp6iJ6N7Bfjo',
    appId: '1:514383062976:ios:81b1a4b065f0ebd14d4a25',
    messagingSenderId: '514383062976',
    projectId: 'smarthomeapp-77bf1',
    storageBucket: 'smarthomeapp-77bf1.appspot.com',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpGoICQrn1SxPhtJ3H3wQp6iJ6N7Bfjo',
    appId: '1:514383062976:ios:81b1a4b065f0ebd14d4a25',
    messagingSenderId: '514383062976',
    projectId: 'smarthomeapp-77bf1',
    storageBucket: 'smarthomeapp-77bf1.appspot.com',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOOiBkPX9NAAriuF_sJjWs50KaoDE4TSA',
    appId: '1:514383062976:web:3bef4960fc7381ab4d4a25',
    messagingSenderId: '514383062976',
    projectId: 'smarthomeapp-77bf1',
    authDomain: 'smarthomeapp-77bf1.firebaseapp.com',
    storageBucket: 'smarthomeapp-77bf1.appspot.com',
  );
}
